### PR TITLE
Automate

### PR DESCRIPTION
**Pull request by mmlb**

### CODE REVIEW

**Comment by mmlb** [comment]
SciLinux is failing to build on my local system, probably due to `vsyscall`. I'll do some more investigating.

**Comment by mmlb** [comment]
I'm getting:
```
Step 4/10 : RUN yum install ${YUM_OPTS} -y      bash    bash-completion         ca-certificates         cron    curl    device-mapper-multipath         dmidecode       e2fsprogs  ethstatus       ioping  iotop   iperf   iscsi-initiator-utils   libmlx4-static  libselinux-python       make    mdadm   mg      mtr     net-tools       ntp     ntpdate    openssh-server  policycoreutils-python  python-argparse         python-cheetah  python-configobj        python-requests         PyYAML  redhat-lsb-core         rsync      screen  socat   sudo    sysstat         tar     tcpdump         tmux    traceroute      vim     wget    && yum clean all
 ---> Running in e8865a29436d
rpmdb: mmap: Operation not permitted
error: db3 error(1) from dbenv->open: Operation not permitted
error: cannot open Packages index using db3 - Operation not permitted (1)
error: cannot open Packages database in /var/lib/rpm
CRITICAL:yum.main:

Error: rpmdb open failed
The command '/bin/sh -c yum install ${YUM_OPTS} -y      bash    bash-completion         ca-certificates         cron    curl    device-mapper-multipath         dmidecode e2fsprogs        ethstatus       ioping  iotop   iperf   iscsi-initiator-utils   libmlx4-static  libselinux-python       make    mdadm   mg      mtr     net-tools       ntp        ntpdate         openssh-server  policycoreutils-python  python-argparse         python-cheetah  python-configobj        python-requests         PyYAML  redhat-lsb-core    rsync   screen  socat   sudo    sysstat         tar     tcpdump         tmux    traceroute      vim     wget    && yum clean all' returned a non-zero code: 1
Makefile:26: recipe for target 'distros/scientific/6/x86_64/image-rootfs.tar.gz' failed
make: *** [distros/scientific/6/x86_64/image-rootfs.tar.gz] Error 1
```

**Comment by Knight1** [comment]
Would you please add a gpg and sha check? 👍

**Comment by mmlb** [comment]
@Knight1  done

**Pull request merged**
